/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface ICreateEntries {
  entries: {
    due_date: string;
    title: string;
  }[];
}

export interface IDeleteEntry {
  id: number;
}

export interface IUpdateEntry {
  data: {
    due_date?: string;
    title?: string;
  };
  id: number;
}
